baseURL = "https://kleinreveche.com/"
languageCode = "en-us"
title = "Klein Reveche"
theme = "dream"

summaryLength = 70
paginate = 10
# Google Analytics ID, Uncomment below line to enable
# googleAnalytics = "UA-123-45"

# Enter your disqus Shortname and uncomment below line to enable
# disqusShortname = "yourdiscussshortname"

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#121212"
  #backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Klein Reveche"
  description = "Ur Average 17 year old with basic programming knowledge"
  avatar = "/images/me/portrait_tux.jpg"
  motto = ""
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  #rss = true

  #utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "therealklr2003@gmail.com"
  twitter = "KleinReveche"
  facebook = "klr2003"
  #instagram = ""
  # mastodon = ""
  #linkedin = ""
  github = "KleinReveche"
  #stackoverflow = ""
  #codepen = ""

  siteStartYear = 2020

  favicon = "/images/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
