baseURL = "https://kleinreveche.com"
languageCode = "en-us"
title = "Klein Reveche"
Paginate = 2
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Klein Reveche"
  description = "My Site"
  message = "Hello"
  hideAutoMenu = false

#[[menu.main]]
#  name = "External"
#  url = "https://example.com"

[social]
  facebook = "https://facebook.com/klr2003"
  twitter = "https://twitter.com/KleinReveche"
  #instagram = "https://instagram.com"
  #linkedin = "https://linkedin.com"